# Generated by Django 5.0.1 on 2024-02-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsletter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newsletter.newsletter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscriber_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
