# Generated by Django 5.0.1 on 2024-02-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_post_newsletter_alter_newsletter_last_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='newsletter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='newsletter.newsletter'),
            preserve_default=False,
        ),
    ]
