# Generated by Django 5.0.1 on 2024-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_subscriber_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscription_confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription_status',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='received_email_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
