# Generated by Django 5.0.1 on 2024-02-08 17:52

import newsletter.utils.hash
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_subscriber_subscription_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='confirmed_subscriber_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription_token',
            field=models.CharField(blank=True, default=newsletter.utils.hash.create_hash, editable=False, max_length=1000, null=True),
        ),
    ]
