# Generated by Django 5.0.1 on 2024-02-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newsletter_confirmed_subscriber_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='verification_email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='verification_email_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='welcome_email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='welcome_email_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
