# Generated by Django 5.0.1 on 2024-02-08 19:20

import django.db.models.deletion
import newsletter.utils.hash
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_newsletter_verification_email_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['created_at'], 'verbose_name': 'Bülten', 'verbose_name_plural': 'Bültenler'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at'], 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['subscribed_at'], 'verbose_name': 'Abone', 'verbose_name_plural': 'Aboneler'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='confirmed_subscriber_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Onaylanmış Abone Sayısı'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Son Gönderi Tarihi'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bülten Adı'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_stats',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Bülten İstatistikleri'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscriber_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Abone Sayısı'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='verification_email_content',
            field=models.TextField(blank=True, null=True, verbose_name='Doğrulama E-Posta İçeriği'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='verification_email_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğrulama E-Posta Konusu'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='welcome_email_content',
            field=models.TextField(blank=True, null=True, verbose_name='Hoşgeldiniz E-Posta İçeriği'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='welcome_email_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hoşgeldiniz E-Posta Konusu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newsletter.newsletter', verbose_name='Bülten'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Posta Adresi'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='newsletter.newsletter', verbose_name='Bülten'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='received_email_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Alınan E-Posta Sayısı'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Abonelik Tarihi'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_confirmed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Abonelik Onayı'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Abonelik Durumu'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_token',
            field=models.CharField(blank=True, default=newsletter.utils.hash.create_hash, editable=False, max_length=1000, null=True, verbose_name='Abonelik Doğrulama Kodu'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Abonelikten Ayrılma Tarihi'),
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='newsletters',
        ),
    ]
