# Generated by Django 5.0.1 on 2024-02-10 13:10

import newsletter.utils.hash
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='access_token',
            field=models.CharField(default=newsletter.utils.hash.create_hash, editable=False, max_length=200, verbose_name='Yorumun Tokeni'),
        ),
    ]
