# Generated by Django 5.0.1 on 2024-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Şikayet Sayısı'),
        ),
    ]
