# Generated by Django 5.0.1 on 2024-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='E-Posta Bildirimi'),
        ),
    ]
