# Generated by Django 5.0.1 on 2024-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
