# Generated by Django 5.0.1 on 2024-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='genre',
        ),
    ]
