# Generated by Django 5.0.1 on 2024-02-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_article_type_article_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
