# Generated by Django 5.0.1 on 2024-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_options_alter_article_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='article_images/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Yazılma Tarihi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('Dizi Hikayeler', 'Dizi Hikayeler'), ('Öyküler', 'Öyküler'), ('Denemeler', 'Denemeler'), ('Kaynak Tavsiyeleri', 'Kaynak Tavsiyeleri'), ('Kitap Yorumları', 'Kitap Yorumları')], default='Dizi Hikayeler', max_length=200, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=200, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Beğeni Sayısı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
