# Generated by Django 5.0.1 on 2024-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_alter_book_date_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
