# Generated by Django 5.0.1 on 2024-02-09 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options_remove_book_impression_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Berker Okan', max_length=200, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
