# Generated by Django 5.0.1 on 2024-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_author_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=2, null=True, verbose_name='Değerlendirme Puanı (5 üzerinden - Site İçi)'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Değerlendirme Sayısı (Site İçi)'),
        ),
    ]
