# Generated by Django 5.0.1 on 2024-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='highlight_book',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan Kitap'),
        ),
        migrations.AddField(
            model_name='book',
            name='highlight_email_content',
            field=models.TextField(blank=True, null=True, verbose_name='Öne Çıkan E-Posta İçeriği'),
        ),
        migrations.AddField(
            model_name='book',
            name='highlight_email_subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Öne Çıkan E-Posta Konusu'),
        ),
        migrations.AddField(
            model_name='book',
            name='send_email_to_subscribers',
            field=models.BooleanField(default=False, verbose_name='Abonelere E-Posta Gönder'),
        ),
    ]
