# Generated by Django 5.0.1 on 2024-02-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at'], 'verbose_name': 'Albüm', 'verbose_name_plural': 'Albümler'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fotoğraf', 'verbose_name_plural': 'Fotoğraflar'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='impression_count',
        ),
        migrations.AddField(
            model_name='album',
            name='engagement_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Etkileşim Sayısı'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='album_images/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='album',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album', verbose_name='Albüm'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
